### ISSUE TITLE
app won't open mac

### ISSUE THREAD

**Issue by MarkJThomas** [move-ucsb/DynamoVis#7]
I have been trying to open the app following the instructions but it won't open.

> Java 15 installed:
/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home

Steps to opening it:

- Double clicked DynamoVis-1.0 nothing opened

- In terminal I run ./run_unix.sh, it just says 'appending output to nohup.out' then the java icon opens the closes straight away.

- java -jar DynamoVis-1.0.jar and I get this message:

```Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: class main.DesktopPane (in unnamed module @0x1796cf6c) cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @0x1796cf6c
	at main.DesktopPane.<init>(DesktopPane.java:207)
	at main.DesktopPane$8.run(DesktopPane.java:729)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)


```

Any help would be greatly appreciated

**Comment by MarkJThomas** [comment]
I downloaded java version 15.0.2 and it now works :D

**Comment by merttoka** [comment]
I am glad Java 15.0.2 solved this issue. I will look into making it work with Java 15.0 too.
